[build]
  publish = "_site"
  command = "npx eleventy"

[[redirects]]
  from = "/es/groupos/*"
  to = "/es/grupos/:splat"
  status = 301

[[redirects]]
  from = "/es/groupos"
  to = "/es/grupos/"
  status = 301

[[redirects]]
  from = "/en/schedule/*"
  to = "/en/program/:splat"
  status = 301

[[redirects]]
  from = "/en/schedule"
  to = "/en/program/"
  status = 301

[[redirects]]
  from = "/es/cronograma/*"
  to = "/es/programa/:splat"
  status = 301

[[redirects]]
  from = "/es/cronograma"
  to = "/es/programa/"
  status = 301

[[redirects]]
  from = "/en/map"
  to = "/en/work-adventure/"
  status = 301
  force = true

[[redirects]]
  from = "/es/mapa"
  to = "/es/work-adventure/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/*"
  to = "/fr/:splat"
  status = 302
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
